version: '3'
services:
  phpservermon-dkr:
    image: phpservermon
    container_name: phpservermon-dkr
    restart: always
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/:rw
    ports:
      - 8089:80
    expose:
      - 8089
  phpservermon-scheduler-dkr:
    image: phpservermon
    container_name: phpservermon-scheduler-dkr
    depends_on:
      - phpservermon-dkr
    volumes:
      - .:/var/www/
    environment:
      CONTAINER_ROLE: scheduler
networks:
  default:
    external:
      name: webproxy
